### ISSUE TITLE
Unable to install APK

### ISSUE THREAD

**Issue by Sketcher** [GreatApo/GreatFit#59] opened 2019-08-12 17:40 UTC
Hi,
I am unable to install APK after I built in Android Studio.
Each time I try it says "Failure [INSTALL_PARSE_FAILED_NO_CERTIFICATES]". I tried everything to fix, but I just can't seem to work out the issue. Help would be appreciated

**Comment by GreatApo** [comment] 2019-08-12 17:58
This indicates that the apk is not signed. You need to create a certificate in Android Studio. I would provide more info but I am not a pro too.

Try the second answer proposed [here](https://stackoverflow.com/questions/20268520/generate-signed-apk-android-studio)

I am closing the issue, feel free to re-comment if you need further help.

**Comment by Sketcher** [comment] 2019-08-12 21:34
I don't want to bother you I know you're not tech support but since you developed the app you know better.
The APK is signed and I use the same key for everything I even tried it out on AmazMod-dev and everything worked without any issue. I even did a factory reset on the watch and even that didn't solve the issue, on your older builds I didn't have this problem and I've been scratching my head and googling trying different methods so I figured I ask you if you encoutered this and maybe could help. Maybe it has something to do with WOS 2.6.6.0 ?

**Comment by GreatApo** [comment] 2019-08-12 23:03
No it's fine you don't bother me. The problem is that I am still a noob when it comes Android Studio!

I think the error definitely points to signing. Try removing any sign config and just build the APK (uninstall the previous version before installing)

**Closed** 2019-08-22 13:39 UTC
Labels: question
